### ISSUE TITLE
Java9 runtime - SAX Parser IO Exception java.net.MalformedURLException: null

### ISSUE THREAD

**Issue by Pitterling** [vlsi/ksar#123]
```console
2018-01-27 00:07:07.439 [main] ERROR net.atomique.ksar.XMLConfig - SAX Parser IO Exception
java.net.MalformedURLException: null
	at java.net.URL.<init>(Unknown Source) ~[?:?]
	at java.net.URL.<init>(Unknown Source) ~[?:?]
	at java.net.URL.<init>(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[?:?]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source) ~[?:?]
	at javax.xml.parsers.SAXParser.parse(Unknown Source) ~[?:?]
	at net.atomique.ksar.XMLConfig.load_config(XMLConfig.java:65) [ksar-5.2.4-SNAPSHOT-all.jar:5.2.4-SNAPSHOT]
	at net.atomique.ksar.XMLConfig.<init>(XMLConfig.java:40) [ksar-5.2.4-SNAPSHOT-all.jar:5.2.4-SNAPSHOT]
	at net.atomique.ksar.GlobalOptions.<init>(GlobalOptions.java:58) [ksar-5.2.4-SNAPSHOT-all.jar:5.2.4-SNAPSHOT]
	at net.atomique.ksar.GlobalOptions.<clinit>(GlobalOptions.java:30) [ksar-5.2.4-SNAPSHOT-all.jar:5.2.4-SNAPSHOT]
	at net.atomique.ksar.Main.main(Main.java:79) [ksar-5.2.4-SNAPSHOT-all.jar:5.2.4-SNAPSHOT]
Caused by: java.lang.NullPointerException
	... 24 more
```

**Comment by toddInPortland** [comment]
The description above is true for jdk-9.0.1, but appears to work for jdk1.8.0_121.
