### ISSUE TITLE
spec null on ksar-5.2.3-all.jar

### ISSUE THREAD

**Issue by rbadillarx** [vlsi/ksar#255]
Got this error (windows 10 pro 21H2) no matter if use:
a) openjdk 18
b) aopenjdk 17
c) oracle jdk 10 
d) amazon jdk

$ "c:\Program Files\non-installed\openjdk-18\bin\java.exe" -jar ksar-5.2.3-all.jar
java.net.MalformedURLException: Cannot invoke "String.length()" because "spec" is null
        at java.base/java.net.URL.<init>(URL.java:708)
        at java.base/java.net.URL.<init>(URL.java:569)
        at java.base/java.net.URL.<init>(URL.java:516)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:650)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1397)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1363)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:257)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1152)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1040)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:943)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
        at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
        at net.atomique.ksar.XMLConfig.load_config(XMLConfig.java:68)
        at net.atomique.ksar.XMLConfig.<init>(XMLConfig.java:43)
        at net.atomique.ksar.GlobalOptions.<init>(GlobalOptions.java:62)
        at net.atomique.ksar.GlobalOptions.<clinit>(GlobalOptions.java:34)
        at net.atomique.ksar.Main.main(Main.java:90)
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "spec" is null
        at java.base/java.net.URL.<init>(URL.java:614)
        ... 23 more

 C:\Program Files (x86)\non-installed\ksar-5.2.3
$ "c:\Program Files\non-installed\openjdk-18\bin\java.exe" --list-modules ksar-5.2.3-all.jar
java.base@18.0.2
java.compiler@18.0.2
java.datatransfer@18.0.2
java.desktop@18.0.2
java.instrument@18.0.2
java.logging@18.0.2
java.management@18.0.2
java.management.rmi@18.0.2
java.naming@18.0.2
java.net.http@18.0.2
java.prefs@18.0.2
java.rmi@18.0.2
java.scripting@18.0.2
java.se@18.0.2
java.security.jgss@18.0.2
java.security.sasl@18.0.2
java.smartcardio@18.0.2
java.sql@18.0.2
java.sql.rowset@18.0.2
java.transaction.xa@18.0.2
java.xml@18.0.2
java.xml.crypto@18.0.2
jdk.accessibility@18.0.2
jdk.attach@18.0.2
jdk.charsets@18.0.2
jdk.compiler@18.0.2
jdk.crypto.cryptoki@18.0.2
jdk.crypto.ec@18.0.2
jdk.crypto.mscapi@18.0.2
jdk.dynalink@18.0.2
jdk.editpad@18.0.2
jdk.hotspot.agent@18.0.2
jdk.httpserver@18.0.2
jdk.incubator.foreign@18.0.2
jdk.incubator.vector@18.0.2
jdk.internal.ed@18.0.2
jdk.internal.jvmstat@18.0.2
jdk.internal.le@18.0.2
jdk.internal.opt@18.0.2
jdk.internal.vm.ci@18.0.2
jdk.internal.vm.compiler@18.0.2
jdk.internal.vm.compiler.management@18.0.2
jdk.jartool@18.0.2
jdk.javadoc@18.0.2
jdk.jcmd@18.0.2
jdk.jconsole@18.0.2
jdk.jdeps@18.0.2
jdk.jdi@18.0.2
jdk.jdwp.agent@18.0.2
jdk.jfr@18.0.2
jdk.jlink@18.0.2
jdk.jpackage@18.0.2
jdk.jshell@18.0.2
jdk.jsobject@18.0.2
jdk.jstatd@18.0.2
jdk.localedata@18.0.2
jdk.management@18.0.2
jdk.management.agent@18.0.2
jdk.management.jfr@18.0.2
jdk.naming.dns@18.0.2
jdk.naming.rmi@18.0.2
jdk.net@18.0.2
jdk.nio.mapmode@18.0.2
jdk.random@18.0.2
jdk.sctp@18.0.2
jdk.security.auth@18.0.2
jdk.security.jgss@18.0.2
jdk.unsupported@18.0.2
jdk.unsupported.desktop@18.0.2
jdk.xml.dom@18.0.2
jdk.zipfs@18.0.2

But  ksar-5.2.4-b396_gf0680721-SNAPSHOT-all.jar almost fine.

**Comment by Pitterling** [comment]
quite old release and never tried with other JAVA versions then 8 ..

Maybe related to old Gradle version ..
https://stackoverflow.com/questions/65409720/net-sf-jasperreports-engine-jrexception-java-net-malformedurlexception-cannot

closing as this version should anyway not be used at all
