### ISSUE TITLE
Fails to connect to X

### ISSUE THREAD

**Issue by dfl1955** [vlsi/ksar#270]
I have downloaded your 5.2.3 and am trying to run this on Raspbian Desktop

When run as super user, I get an error fails to connect to X. 

```
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':10.0' as the value of the DISPLAY variable.
	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
```
This error does not occur when running the Java Xclock app, nor if I call xeyes.

The attached log includes the java stack dump, the current $DISPLAY value, the output from uname, env | grep X  and apt-cache show xfce4. and cat /etc/*release.

Is this a code bug or a configuration error?

[java.log](https://github.com/vlsi/ksar/files/10374583/java.log)

Dave

**Comment by Pitterling** [comment]
No, clue. Just searched the web and found this

https://stackoverflow.com/questions/10165761/java-cant-connect-to-x11-window-server-using-localhost10-0-as-the-value-of-t

Any suggestion helpful?

**Comment by dfl1955** [comment]
Yes, the advice about using xhost was useful, but I get another error. Can you see if you can help? 

`java.net.MalformedURLException
	at java.base/java.net.URL.<init>(URL.java:679)`

[errorlog2.txt](https://github.com/vlsi/ksar/files/10392113/errorlog2.txt)

I wonder if it's the location of the sar database that's the problem. I am now testing this on Ubuntu 22.04 on Virtual Box.

**Comment by Pitterling** [comment]
Search issues here for "SAXParser". You need to use a snapshot version instead of 5.2.3. 

Snapshot versions are also available on the release page.

**Comment by dfl1955** [comment]
I downloaded the most recent snapshot and it seems to work. It generates an error as it boots which I have attached, but this is now working for me, Thank you for your help. 

`2023-01-15 18:51:17,495 main ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.FileAppender for element File: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.FileAppender java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.FileAppender
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:234)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:134)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:622)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:695)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:712)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:267)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:155)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at net.atomique.ksar.Main.<clinit>(Main.java:21)

2023-01-15 18:51:17,500 main ERROR Null object returned for File in appenders.
2023-01-15 18:51:17,517 main ERROR Unable to locate appender "MyFile" for logger config "root"
`

**Comment by Pitterling** [comment]
Might be related to missing write permission for the log file ksar_all.log which is created in the same directory where the jar is located.
