### ISSUE TITLE
NPE during file parsing with MM/DD/YYYY AM|PM date

### ISSUE THREAD

**Issue by mormih** [vlsi/ksar#57]
```
unable to parse date 09/15/2016
Exception in thread "Thread-6" java.lang.NullPointerException: date
        at java.util.Objects.requireNonNull(Objects.java:228)
        at java.time.LocalDateTime.of(LocalDateTime.java:374)
        at net.atomique.ksar.Parser.Linux.parse(Linux.java:102)
        at net.atomique.ksar.kSar.parse(kSar.java:145)
        at net.atomique.ksar.FileRead.run(FileRead.java:78)
```
[devsp105cn_14_09_2016.txt](https://github.com/vlsi/ksar/files/568723/devsp105cn_14_09_2016.txt)

**Comment by Pitterling** [comment]
Hi, the file has an unsupported date/time format
09/14/**2016** - 12:00:01 AM

as a workaround change the year to 16.
09/14/**16** - 12:00:01 AM

btw .. you have a memory/paging issue ;)

handling the date/time formats is on the list to be improved
