### ISSUE TITLE
kSar.version missing in artifact 5.2.0

### ISSUE THREAD

**Issue by L-Francois** [vlsi/ksar#96]
Hello,

A small typo in this jar which breaks pdf export:

https://github.com/vlsi/ksar/releases/download/v5.2.0/ksar-5.2.0-all.jar

C:\temp\sar-gamma>java -jar ksar-5.2.0-all.jar
exit
Exception in thread "Thread-4" java.lang.ExceptionInInitializerError
        at net.atomique.ksar.Export.FilePDF.run(FilePDF.java:96)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Unknown Source)
        at java.io.InputStreamReader.<init>(Unknown Source)
        at net.atomique.ksar.VersionNumber.<init>(VersionNumber.java:30)
        at net.atomique.ksar.VersionNumber.<clinit>(VersionNumber.java:19)
        ... 2 more

I had to use this older version due to other issues.

Best regards,
Francois

**Comment by Pitterling** [comment]
this has been fixed with 5.2.1 .. whats wrong with this or higher versions?

**Comment by Pitterling** [comment]
no update for long time .. closing ... just reopen if needed
